server:
  port: 10010
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  application:
    name: web-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka