server:
  port: 8888
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true